// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCF86-_LNrbow6fX2DrW6Y1woyxCdAFLM',
    appId: '1:26246770061:web:ebb46f72531f5a2ade61c4',
    messagingSenderId: '26246770061',
    projectId: 'fir-register-1913',
    authDomain: 'fir-register-1913.firebaseapp.com',
    storageBucket: 'fir-register-1913.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JZJOkl8Y6Gs1N9VMwo1jFZPAmUDFhXY',
    appId: '1:26246770061:android:fc1910094818d622de61c4',
    messagingSenderId: '26246770061',
    projectId: 'fir-register-1913',
    storageBucket: 'fir-register-1913.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vZumVik0fUIa3CYyd0I-U9pHeCxD2VY',
    appId: '1:26246770061:ios:343839a5fc9df206de61c4',
    messagingSenderId: '26246770061',
    projectId: 'fir-register-1913',
    storageBucket: 'fir-register-1913.appspot.com',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vZumVik0fUIa3CYyd0I-U9pHeCxD2VY',
    appId: '1:26246770061:ios:d94522ed8e28567fde61c4',
    messagingSenderId: '26246770061',
    projectId: 'fir-register-1913',
    storageBucket: 'fir-register-1913.appspot.com',
    iosBundleId: 'com.example.firebaseConnection.RunnerTests',
  );
}
